development:
  database: simple_backend_example_development
  encoding: unicode
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  user: root
  password:
  min_messages: WARNING

test:
  database: simple_backend_example_test
  encoding: unicode
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  user: root
  password:
  min_messages: WARNING

production:
  database: simple_backend_example_production
  encoding: unicode
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  user: root
  password:
  min_messages: WARNING
